In [ ]:
import numpy as np   #create array with zeros
a = np.zeros((2,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
a = np.ones((3,4))   #create array with ones
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
c = np.full((2,3),4)     #create array with whatever number u want
print(c)

[[4 4 4]
 [4 4 4]]


In [ ]:
a = np.eye(3)     #create identity matrix
print(a)     

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as ana

In [ ]:
a = ana.random.random((3,3))
print(a)

[[0.94149849 0.72115538 0.18265836]
 [0.55291792 0.9042676  0.12595844]
 [0.46171988 0.33760363 0.22062821]]


In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])
temp = a[0:2,1:3]
print(temp)

[[2 3]
 [6 7]]


In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

print(ana.add(x,y))

[[ 6  8]
 [10 12]]


In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

print(ana.subtract(x,y))

[[-4 -4]
 [-4 -4]]


In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

print(ana.multiply(x,y))

[[ 5 12]
 [21 32]]


In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

print(ana.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
x = ana.array([[1,2],[3,4]])
x.max(axis=1)

array([2, 4])

In [ ]:
print("Transpose;",x.T)   #Transpose the matrix

Transpose; [[1 3]
 [2 4]]
